import { Product } from "@/types";

export const CATEGORIES = [
  {
    id: "adult-cycles",
    name: "Adult Cycles",
    slug: "adult-cycles",
    description: "Premium road, mountain, and hybrid cycles for adults",
    subcategories: [
      { id: "mountain-bikes", name: "Mountain Bikes", slug: "mountain-bikes" },
      { id: "road-bikes", name: "Road Bikes", slug: "road-bikes" },
      { id: "hybrid-bikes", name: "Hybrid Bikes", slug: "hybrid-bikes" },
      { id: "electric-cycles", name: "Electric Cycles", slug: "electric-cycles" },
    ],
  },
  {
    id: "kids-bicycles",
    name: "Kids Bicycles",
    slug: "kids-bicycles",
    description: "Safe, fun, and durable bicycles for children",
    subcategories: [
      { id: "balance-bikes", name: "Balance Bikes", slug: "balance-bikes" },
      { id: "training-wheels", name: "With Training Wheels", slug: "training-wheels" },
      { id: "kids-mountain", name: "Kids Mountain Bikes", slug: "kids-mountain" },
    ],
  },
  {
    id: "accessories",
    name: "Accessories",
    slug: "accessories",
    description: "Helmets, locks, lights, and spare parts",
    subcategories: [
      { id: "helmets", name: "Helmets", slug: "helmets" },
      { id: "locks", name: "Locks & Security", slug: "locks" },
      { id: "lights", name: "Lights & Reflectors", slug: "lights" },
      { id: "spare-parts", name: "Spare Parts", slug: "spare-parts" },
    ],
  },
];

export const NAV_LINKS = [
  { name: "Bicycles", href: "/category/adult-cycles" },
  { name: "Kids Bikes", href: "/category/kids-bicycles" },
  { name: "Cycling Accessories", href: "/category/accessories" },
  { name: "Accessories", href: "/category/accessories" },
  { name: "Offers", href: "/offers" },
  { name: "Blogs", href: "/blogs" },
];

export const SORT_OPTIONS = [
  { label: "Featured", value: "featured" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Price: High to Low", value: "price-desc" },
  { label: "Newest", value: "newest" },
  { label: "Best Rated", value: "rating" },
];

export const ORDER_STATUSES = {
  pending: { label: "Pending", color: "bg-yellow-100 text-yellow-800" },
  processing: { label: "Processing", color: "bg-blue-100 text-blue-800" },
  shipped: { label: "Shipped", color: "bg-purple-100 text-purple-800" },
  delivered: { label: "Delivered", color: "bg-green-100 text-green-800" },
  cancelled: { label: "Cancelled", color: "bg-red-100 text-red-800" },
  refunded: { label: "Refunded", color: "bg-gray-100 text-gray-800" },
};

export const BRANDS = [
  "Trek", "Specialized", "Canyon", "Giant", "Cannondale",
  "BMX Star", "Hero Cycles", "Atlas", "Hercules", "Firefox",
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "TrailBlazer MTB Pro 27.5",
    description: "Conquer any terrain with the TrailBlazer MTB Pro. Featuring a lightweight alloy frame, 21-speed Shimano drivetrain, and hydraulic disc brakes for maximum control.",
    price: 129900,
    salePrice: 99900,
    categoryId: "mountain-bikes",
    brand: "Trek",
    images: ["https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&q=80&w=800"],
    thumbnail: "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&q=80&w=800",
    stock: 15,
    specifications: {
      "Frame": "6061 Alloy, Hydroformed",
      "Fork": "SR Suntour XCR32 Air",
      "Drivetrain": "Shimano Deore 21-speed",
      "Brakes": "Hydraulic Disc",
      "Wheels": "27.5 inch",
      "Weight": "14.2 kg",
    },
    features: [
      "Hydraulic disc brakes for all-weather stopping power",
      "Tubeless-ready wheels",
      "Dropper post compatible",
      "Internal cable routing",
    ],
    warrantyInfo: "5 years frame warranty, 1 year components",
    rating: 4.8,
    reviewsCount: 124,
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now(),
    isActive: true,
    tags: ["mountain", "adult", "trail", "21-speed"],
  },
  {
    id: "p2",
    name: "CityGlide Hybrid 700C",
    description: "The perfect urban commuter. Lightweight, comfortable, and packed with features to make your daily ride a pleasure.",
    price: 74900,
    salePrice: undefined,
    categoryId: "hybrid-bikes",
    brand: "Giant",
    images: ["https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&q=80&w=800"],
    thumbnail: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800",
    stock: 22,
    specifications: {
      "Frame": "ALUXX Aluminum",
      "Handlebar": "Flat Bar",
      "Drivetrain": "Shimano 7-speed",
      "Brakes": "Tektro Mechanical Disc",
      "Wheels": "700C x 35mm",
      "Weight": "12.1 kg",
    },
    features: [
      "Comfortable upright geometry",
      "Integrated fender and rack mounts",
      "Reflective sidewall tires",
    ],
    warrantyInfo: "Lifetime frame warranty",
    rating: 4.6,
    reviewsCount: 87,
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now(),
    isActive: true,
    tags: ["hybrid", "commuter", "adult", "city"],
  },
  {
    id: "p3",
    name: "SparkKid 20\" Adventure",
    description: "Built for young adventurers who are ready to take on the trails. Lightweight frame, easy-grip brakes, and fun colors.",
    price: 29900,
    salePrice: 24900,
    categoryId: "kids-mountain",
    brand: "Hero Cycles",
    images: ["https://images.unsplash.com/photo-1511994298241-608e28f14fde?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&q=80&w=800"],
    thumbnail: "https://images.unsplash.com/photo-1511994298241-608e28f14fde?auto=format&fit=crop&q=80&w=800",
    stock: 40,
    specifications: {
      "Frame": "Hi-Ten Steel",
      "Wheel Size": "20 inch",
      "Speeds": "6",
      "Brakes": "V-Brakes",
      "Age Range": "6-10 years",
      "Weight": "9.5 kg",
    },
    features: [
      "Easy-to-use twist shifters",
      "Chain guard included",
      "Adjustable seat height",
    ],
    warrantyInfo: "1 year warranty",
    rating: 4.7,
    reviewsCount: 203,
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now(),
    isActive: true,
    tags: ["kids", "20-inch", "adventure"],
  },
  {
    id: "p4",
    name: "Lightning Bolt Electric 48V",
    description: "Experience effortless city riding with 48V motor, 60km range, and smart display. The future of urban transport.",
    price: 249900,
    salePrice: 219900,
    categoryId: "electric-cycles",
    brand: "Canyon",
    images: ["https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1511994298241-608e28f14fde?auto=format&fit=crop&q=80&w=800"],
    thumbnail: "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&q=80&w=800",
    stock: 8,
    specifications: {
      "Motor": "250W Hub Motor",
      "Battery": "48V 12Ah Li-Ion",
      "Range": "Up to 60km",
      "Max Speed": "25 km/h",
      "Charging Time": "4-5 hours",
      "Weight": "22 kg",
    },
    features: [
      "5 pedal assist levels",
      "Integrated LED display",
      "USB charging port",
      "Regenerative braking",
    ],
    warrantyInfo: "2 years battery, 3 years frame",
    rating: 4.9,
    reviewsCount: 56,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
    isActive: true,
    tags: ["electric", "ebike", "commuter", "adult"],
  },
  {
    id: "p5",
    name: "Carbon Road Racer X",
    description: "Ultra-light carbon fiber road bike designed for speed and endurance. Shimano 105 groupset and aerodynamic profile.",
    price: 189900,
    salePrice: 175900,
    categoryId: "road-bikes",
    brand: "Specialized",
    images: ["https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1511994298241-608e28f14fde?auto=format&fit=crop&q=80&w=800"],
    thumbnail: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&q=80&w=800",
    stock: 12,
    specifications: {
      "Frame": "Advanced Grade Composite",
      "Fork": "Full Carbon",
      "Drivetrain": "Shimano 105 11-speed",
      "Brakes": "Hydraulic Disc",
      "Wheels": "700C Carbon",
      "Weight": "8.2 kg",
    },
    features: [
      "Aerodynamic tube shapes",
      "Integrated cable routing",
      "Tubeless-ready wheels",
    ],
    warrantyInfo: "Lifetime frame warranty",
    rating: 4.8,
    reviewsCount: 94,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
    isActive: true,
    tags: ["road", "racing", "carbon", "adult"],
  },
  {
    id: "p6",
    name: "BMX Trickster 20",
    description: "Built tough for the skatepark or dirt jumps. Hi-Ten steel frame, 3-piece crank, and U-brakes.",
    price: 34900,
    salePrice: 29900,
    categoryId: "mountain-bikes",
    brand: "BMX Star",
    images: ["https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800"],
    thumbnail: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800",
    stock: 25,
    specifications: {
      "Frame": "Hi-Ten Steel",
      "Fork": "Chromoly Steerer",
      "Crankset": "3-Piece Tubular Chromoly",
      "Brakes": "Alloy U-Brake",
      "Wheels": "20 inch",
      "Weight": "11.5 kg",
    },
    features: [
      "Rotor for 360-degree bar spins",
      "4 pegs included",
      "High-grip tires",
    ],
    warrantyInfo: "1 year frame warranty",
    rating: 4.5,
    reviewsCount: 62,
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now(),
    isActive: true,
    tags: ["bmx", "stunt", "youth"],
  },
  {
    id: "p7",
    name: "Aero Helmet Pro",
    description: "Lightweight and highly ventilated aerodynamic cycling helmet. Keeps you safe without slowing you down.",
    price: 8900,
    salePrice: undefined,
    categoryId: "helmets",
    brand: "Trek",
    images: ["/helmet.jpg"],
    thumbnail: "/helmet.jpg",
    stock: 45,
    specifications: {
      "Material": "Polycarbonate Shell",
      "Vents": "18",
      "Weight": "240g",
      "Size": "Adjustable Dial",
    },
    features: [
      "MIPS Brain Protection System",
      "Moisture-wicking pads",
      "Magnetic buckle",
    ],
    warrantyInfo: "1 year warranty",
    rating: 4.9,
    reviewsCount: 156,
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now(),
    isActive: true,
    tags: ["helmet", "safety", "accessory"],
  },
  {
    id: "p8",
    name: "Heavy Duty U-Lock",
    description: "Maximum security U-lock made from 14mm hardened steel. Protect your investment from thieves.",
    price: 4500,
    salePrice: 3900,
    categoryId: "locks",
    brand: "Specialized",
    images: ["/lock.jpg"],
    thumbnail: "/lock.jpg",
    stock: 60,
    specifications: {
      "Material": "14mm Hardened Steel",
      "Type": "U-Lock with Cable",
      "Weight": "1.5 kg",
      "Security Rating": "9/10",
    },
    features: [
      "Double deadbolt design",
      "Anti-drill cylinder",
      "Mounting bracket included",
    ],
    warrantyInfo: "Lifetime warranty",
    rating: 4.7,
    reviewsCount: 312,
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now(),
    isActive: true,
    tags: ["lock", "security", "accessory"],
  }
];
